social_auth_reddit.settings:
  type: config_object
  label: 'Social Auth Reddit settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    api_calls:
      type: string
      label: 'API calls which will retrieve data'
    restricted_domain:
      type: string
label: 'Restricted Domain'
