social_auth_reddit.settings:
  type: config_object
  label: 'Social Auth Reddit settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    scopes:
      type: string
      label: 'Scopes to make API calls'
    api_calls:
      type: string
      label: 'API calls which will retrieve data'
    user_agent_string:
      type: string
      label: "User Agent string"
